import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-dim':               '#111319',
        'surface':                   '#111319',
        'surface-container-lowest':  '#0c0e14',
        'surface-container-low':     '#191b22',
        'surface-container':         '#1e1f26',
        'surface-container-high':    '#282a30',
        'surface-container-highest': '#33343b',
        'surface-bright':            '#373940',
        'surface-variant':           '#33343b',
        'surface-tint':              '#c0c1ff',
        'on-surface':                '#e2e2eb',
        'on-surface-variant':        '#c7c4d7',
        'on-background':             '#e2e2eb',
        'inverse-surface':           '#e2e2eb',
        'inverse-on-surface':        '#2e3037',
        'primary':                   '#c0c1ff',
        'primary-container':         '#8083ff',
        'primary-fixed':             '#e1e0ff',
        'primary-fixed-dim':         '#c0c1ff',
        'on-primary':                '#1000a9',
        'on-primary-container':      '#0d0096',
        'on-primary-fixed':          '#07006c',
        'on-primary-fixed-variant':  '#2f2ebe',
        'inverse-primary':           '#494bd6',
        'secondary':                 '#ffb95f',
        'secondary-container':       '#ee9800',
        'secondary-fixed':           '#ffddb8',
        'secondary-fixed-dim':       '#ffb95f',
        'on-secondary':              '#472a00',
        'on-secondary-container':    '#5b3800',
        'on-secondary-fixed':        '#2a1700',
        'on-secondary-fixed-variant':'#653e00',
        'tertiary':                  '#ffb783',
        'tertiary-container':        '#d97721',
        'tertiary-fixed':            '#ffdcc5',
        'tertiary-fixed-dim':        '#ffb783',
        'on-tertiary':               '#4f2500',
        'on-tertiary-container':     '#452000',
        'on-tertiary-fixed':         '#301400',
        'on-tertiary-fixed-variant': '#703700',
        'outline':                   '#908fa0',
        'outline-variant':           '#464554',
        'background':                '#111319',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
      },
      fontFamily: {
        headline: ['var(--font-headline)', 'Georgia', 'serif'],
        body:     ['var(--font-body)',     'system-ui', 'sans-serif'],
        label:    ['var(--font-label)',    'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        full:    '9999px',
      },
      boxShadow: {
        glass:    '0px 4px 20px rgba(0,0,0,0.5), 0px 0px 1px 1px rgba(192,193,255,0.08)',
        'glow-primary': '0 0 40px rgba(192,193,255,0.15)',
        'glow-secondary': '0 0 20px rgba(255,185,95,0.3)',
      },
      animation: {
        'float-slow': 'float 8s ease-in-out infinite',
        'float-slower': 'float 12s ease-in-out infinite reverse',
        'pulse-slow': 'pulse 4s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0px) translateX(0px)' },
          '33%': { transform: 'translateY(-20px) translateX(10px)' },
          '66%': { transform: 'translateY(10px) translateX(-8px)' },
        },
      },
    },
  },
  plugins: [],
}

export default config
